services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-survival
    ports:
      - 25565:25565
    restart: always
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE" # the only required variable
      UID: "1000"
      GID: "1000"
      #ICON: "URL TO ICON"
      MEMORY: 2G 
      TZ: "America/New_York"
      SPAWN_PROTECTION: 0
      ENABLE_ROLLING_LOGS: "true"
      TYPE:  "VANILLA" # default server type which is the Offical Software provided by Mojang
      OPS: "SpifferYew7423"
      VERSION: "LATEST"
      DIFFICULTY: "hard" 
      MODE: "survival"
      SERVER_NAME: "My Survival Minecraft Server"
      MOTD: "My Survival Server"
      MAX_PLAYERS: 10
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      ONLINE_MODE: "true"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      # A list of usernames and/or UUIDs separated by comma
      WHITELIST: "Put,Usernames,here"
      ENABLE_RCON: "false"
      RCON_PASSWORD: "STRONGPASSWORD"
    volumes:
      - ./survivalData:/data
      - ./survivalPlugins:/plugins
      - ./survivalMods:/mods
